# Generated by Django 5.1.7 on 2025-04-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.manager', verbose_name='Manager of Maintainers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
