# Generated by Django 5.1.7 on 2025-04-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_maintainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='name',
            new_name='nameManager',
        ),
    ]
