# Generated by Django 5.1.7 on 2025-04-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_manager_namemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='nameManager',
            new_name='name',
        ),
    ]
