# Generated by Django 5.1.7 on 2025-04-09 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_environment_patrimony_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='maintainer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='maintainer',
            name='ni',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='area',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='ni',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='name',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='ni',
        ),
        migrations.AddField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='normal_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(default='Area', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(default='Cargo', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='ni',
            field=models.CharField(default='sn1', max_length=15),
        ),
    ]
