# Generated by Django 5.1.7 on 2025-04-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_maintainer_area_remove_maintainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimony',
            name='ni',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('opening', models.DateTimeField()),
                ('closing', models.DateTimeField()),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('andamento', 'andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=15)),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], max_length=15)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintainer')),
                ('patrimony', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patrimony')),
                ('responsible', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
            ],
        ),
    ]
